name: Build, Test and Release

on:
  push:
    branches-ignore:
      - 'wip*'
  pull_request:
    branches:
      - 'master'

jobs:
  build_test_release:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version:     '6.0.x'
          include-prerelease: true

      - name: dotnet Build
        run:  dotnet build -c Release /p:ContinuousIntegrationBuild=true

      - name: dotnet Test
        run:  dotnet test -c Release --no-build

      - name: dotnet Pack
        if:   startsWith(github.ref, 'refs/tags/v')
        run:  dotnet pack -c Release --no-build

      - name: Upload artifact
        if:   startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v2
        with:
          path: HttpMultiPart/bin/Release/*nupkg